AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  SpreadsheetId:
    Type: String
  GAuthPrivateKey:
    Type: String
  GAuthClientEmail:
    Type: String

Resources:
  PostRsvp:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      CodeUri: ./post-rsvp
      Runtime: nodejs6.10
      Timeout: 100
      Events:
        PostRsvp:
          Type: Api
          Properties:
            Path: /rsvp
            Method: Post
      Environment:
        Variables:
          SpreadsheetId: !Ref SpreadsheetId
          GAuthPrivateKey: !Ref GAuthPrivateKey
          GAuthClientEmail: !Ref GAuthClientEmail
